import { v4 as uuid } from "uuid";
import product1 from "../../assets/product1.jpg"
import product2 from "../../assets/product2.jpg"
import product3 from "../../assets/product3.jpg"
import product4 from "../../assets/product4.jpg"
import product5 from "../../assets/product5.jpg"
import product6 from "../../assets/product6.jpg"
import product7 from "../../assets/product7.jpg"
import product8 from "../../assets/product8.jpg"
import product9 from "../../assets/product9.jpg"
import product10 from "../../assets/product10.jpg"
import product11 from "../../assets/product11.jpg"
import product12 from "../../assets/product12.jpg"
import product13 from "../../assets/product13.jpg"
import product14 from "../../assets/product14.jpg"
import product15 from "../../assets/product15.jpg"
import product16 from "../../assets/product16.jpg"
import product17 from "../../assets/product17.jpg"
import product18 from "../../assets/product18.jpg"
import product19 from "../../assets/product19.jpg"
import product20 from "../../assets/product20.jpg"
import product21 from "../../assets/product21.jpg"
import product22 from "../../assets/product22.jpg"
import product23 from "../../assets/product23.jpg"
import product24 from "../../assets/product24.jpg"
import product25 from "../../assets/product25.jpg"
import product26 from "../../assets/product26.jpg"
import product27 from "../../assets/product27.jpg"
import product28 from "../../assets/product28.jpg"
import product29 from "../../assets/product29.jpg"
import product30 from "../../assets/product30.jpg"
import product31 from "../../assets/product31.jpg"
import product32 from "../../assets/product32.jpg"
import product33 from "../../assets/product33.jpg"


export const products = [
  {
    _id: uuid(),
    imgUrl: product1,
    description: "Mens Feather Weight White Orange Sneakers",
    isTrending: false,
    isFavourite: false,
    title: "Organic Cow Ghee",
    productCategory: "Cow Ghee",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl: product2,
    isTrending: true,
    description: "Womens Light Weight Black Addidas Running Shoes",
    isFavourite: false,
    title: "Raw Honey",
    productCategory: "Forest Honey",
    newPrice: 750,
    oldPrice: 1499,
    discount: 75,
    outOfStock: true,
    isFast: false,
    itemCategory: "Honey",
    itemRating: 3.9
  },
  {
    _id: uuid(),
    imgUrl: product3,
    isTrending: false,
    description: "Stone pressed mustard oil is made using wood or stone presses, and is chemical-free, preservative-free, and 100% natural. ",
    isFavourite: false,
    title: "Stone Pressed Black Mustard Oil",
    productCategory: "Mustard Oil",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 46,
    outOfStock: false,
    isFast: false,
    itemCategory: "oils",
    itemRating: 2.9
  },
  {
    _id: uuid(),
    imgUrl: product4,
    isTrending: false,
    description: "Womens Light Weight Pink Running Shoes",
    isFavourite: false,
    title: "Wild Raw Honey",
    productCategory: "Multiflora - Premium",
    newPrice: 2554,
    oldPrice: 3499,
    discount: 27,
    outOfStock: false,
    isFast: false,
    itemCategory: "Honey",
    itemRating: 1.1
  },
  {
    _id: uuid(),
    imgUrl: product5,
    isTrending: false,
    description: "Premium Butter made from Almonds, High in monounsaturated fat, low in carbohydrates, and has the highest fiber content",
    isFavourite: false,
    title: "Almond Butter",
    productCategory: "Butter - Premium",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 21,
    outOfStock: true,
    isFast: false,
    itemCategory: "Butter",
    itemRating: 1.8
  },
  {
    _id: uuid(),
    imgUrl: product6,
    isTrending: false,
    description: "Stone cold pressed groundnut oil is extracted from seeds, nuts, or fruits without the use of heat or chemicals, preserving the oil's natural flavors and nutritional value. ",
    isFavourite: false,
    title: "Stone Pressed Groundnut Oil.",
    productCategory: "Groundnut Oil",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 27,
    outOfStock: false,
    isFast: true,
    itemCategory: "oils",
    itemRating: 2.5
  },
  {
    _id: uuid(),
    imgUrl: product7,
    isTrending: false,
    description: "Consumption of Brahmi is linked to reduce ADHD (Attention deficit hyper disorder), prevention of anxiety and stress as well as boosted brain function.",
    isFavourite: false,
    title: "Bhrami Ghee",
    productCategory: "Cow Ghee",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 90,
    outOfStock: false,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 3.6
  },
  {
    _id: uuid(),
    imgUrl: product8,
    isTrending: false,
    description: "Smooth and creamy with a mild, buttery flavor, and lower in fat than other nut butters",
    isFavourite: false,
    title: "Cashew Collection",
    productCategory: "Cashew Butter",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 44,
    outOfStock: true,
    isFast: false,
    itemCategory: "Butter",
    itemRating: 4.2
  },
  {
    _id: uuid(),
    imgUrl: product9,
    isTrending: false,
    description: "Honey made from the Eucalyptus tree",
    isFavourite: false,
    title: "Eucalyptus Honey",
    productCategory: "Forest Honey",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 39,
    outOfStock: false,
    isFast: true,
    itemCategory: "Honey",
    itemRating: 3.5
  },
  {
    _id: uuid(),
    imgUrl: product10,
    isTrending: false,
    description: "made from the milk of indigenous A2 Gir cows.",
    isFavourite: false,
    title: "A-2 Cow-Cultured Ghee",
    productCategory: "Cow Ghee",
    newPrice: 1644,
    oldPrice: 3499,
    discount: 53,
    outOfStock: false,
    isFast: true,
    itemCategory: "Ghee",
    itemRating: 2.7
  },
  {
    _id: uuid(),
    imgUrl: product11,
    isTrending: false,
    description: "Made from the essence of buckwheat plant",
    isFavourite: false,
    title: "Buckwheat Honey",
    productCategory: "Tree Honey",
    newPrice: 1674,
    oldPrice: 2499,
    discount: 33,
    outOfStock: false,
    isFast: false,
    itemCategory: "Honey",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: product12,
    isTrending: false,
    description: "Organically made from tea tree",
    isFavourite: false,
    title: "Manuka Honey",
    productCategory: "Tree Honey",
    newPrice: 899,
    oldPrice: 4499,
    discount: 80,
    outOfStock: false,
    isFast: false,
    itemCategory: "Honey",
    itemRating: 4.1
  },
  {
    _id: uuid(),
    imgUrl: product13,
    isTrending: true,
    description: "Turmeric Ghee could help in treatment of skin disorders and be beneficial in reducing inflammation",
    isFavourite: false,
    title: "Turmeric Ghee",
    productCategory: "Organic Ghee",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 4.9
  },
  {
    _id: uuid(),
    imgUrl: product14,
    isTrending: false,
    description: "a honey produced by honey bees collecting nectar from alfalfa flowers",
    isFavourite: false,
    title: "Alfalfa Honey",
    productCategory: "Tree Honey",
    newPrice: 675,
    oldPrice: 1499,
    discount: 55,
    outOfStock: false,
    isFast: false,
    itemCategory: "Honey",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: product15,
    isTrending: false,
    description: "This is Pure Ghee made from Buffalo milk",
    isFavourite: false,
    title: "Buffalo Ghee",
    productCategory: "Organic Ghee",
    newPrice: 3600,
    oldPrice: 4499,
    discount: 20,
    outOfStock: false,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: product16,
    isTrending: true,
    description: "Stone Cold Pressed Sesame Oil is EXTRACTED with WOODEN CHURNER on Stone Mill . It contains small amounts of alpha-linolenic acid (ALA), a type of omega-3 that is beneficial for heart health and reducing inflammation in the body.",
    isFavourite: false,
    title: "stone pressed Sesame oil",
    productCategory: "Sesame Oil",
    newPrice: 899,
    oldPrice: 4499,
    discount: 80,
    outOfStock: false,
    isFast: false,
    itemCategory: "oils",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: product17,
    isTrending: true,
    description: "Contains fiber, and almost 20 different vitamins and minerals",
    isFavourite: false,
    title: "Pecan Butter",
    productCategory: "Butter",
    newPrice: 3600,
    oldPrice: 4499,
    discount: 20,
    outOfStock: false,
    isFast: false,
    itemCategory: "Butter",
    itemRating: 4.5
  },
  {
    _id: uuid(),
    imgUrl: product18,
    isTrending: false,
    description: "Peanut butter is a food paste of groundnuts.",
    isFavourite: false,
    title: "Peanut butter",
    productCategory: "Butter",
    newPrice: 375,
    oldPrice: 1499,
    discount: 75,
    outOfStock: false,
    isFast: false,
    itemCategory: "Butter",
    itemRating: 1.5
  },
  {
    _id: uuid(),
    imgUrl: product19,
    isTrending: false,
    description: "Made with Hazelnuts, slow roasted at low temperature to maintain the nutrients. ",
    isFavourite: false,
    title: "Hazelnut Butter",
    productCategory: "Butter",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: true,
    itemCategory: "Butter",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl: product20,
    isTrending: false,
    description: "Made from fresh, high-quality coconuts that have been cold pressed and extracted without the use of any chemicals or solvents.",
    isFavourite: false,
    title: "Stone Pressed Virgin Coconut Oil",
    productCategory: "Coconut Oil",
    newPrice: 449,
    oldPrice: 1499,
    discount: 70,
    outOfStock: false,
    isFast: false,
    itemCategory: "oils",
    itemRating: 4.9
  },
  {
    _id: uuid(),
    imgUrl: product21,
    isTrending: false,
    description: "Coconut butter turns shredded coconut turned into creamy coconut butter",
    isFavourite: false,
    title: "Coconut butter",
    productCategory: "Butter",
    newPrice: 494,
    oldPrice: 1499,
    discount: 67,
    outOfStock: false,
    isFast: false,
    itemCategory: "Butter",
    itemRating: 3.5
  },
  {
    _id: uuid(),
    imgUrl: product22,
    isTrending: false,
    description: "Stone Pressed Castor Oil is 100% pure, natural & cold-pressed and is extracted from best quality castor seeds without using any heat or chemical treatment.",
    isFavourite: false,
    title: "Stone Pressed Castor Oil",
    productCategory: "Castor Oil",
    newPrice: 3159,
    oldPrice: 3999,
    discount: 21,
    outOfStock: false,
    isFast: false,
    itemCategory: "oils",
    itemRating: 3.2
  },
  {
    _id: uuid(),
    imgUrl: product23,
    isTrending: false,
    description: "Organic Ashwagandha Ghee is an Ayurvedic herbally-infused ghee.",
    isFavourite: false,
    title: "Ashwagandha ghee",
    productCategory: "Cow Ghee",
    newPrice: 1124,
    oldPrice: 1499,
    discount: 25,
    outOfStock: false,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 2.5
  },
  {
    _id: uuid(),
    imgUrl: product24,
    isTrending: false,
    description: "Acacia honey is made from the nectar of the black locust tree",
    isFavourite: false,
    title: "Acacia honey",
    productCategory: "Tree Honey",
    newPrice: 750,
    oldPrice: 1499,
    discount: 50,
    outOfStock: true,
    isFast: false,
    itemCategory: "Honey",
    itemRating: 3.9
  },
  {
    _id: uuid(),
    imgUrl: product25,
    isTrending: false,
    description: "Organic Shatavari Ghee is an Ayurvedic, shatavari infused grass-fed, organic, cultured ghee",
    isFavourite: false,
    title: "Shatavari Ghee",
    productCategory: "Organic Ghee",
    newPrice: 750,
    oldPrice: 2499,
    discount: 70,
    outOfStock: true,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 1.5
  },
  {
    _id: uuid(),
    imgUrl: product26,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Onion 1kg",
    productCategory: "Vegetables",
    newPrice: 750,
    oldPrice: 2499,
    discount: 70,
    outOfStock: false,
    isFast: false,
    itemCategory: "vegetables",
    itemRating: 4.1
  },
  {
    _id: uuid(),
    imgUrl: product27,
    isTrending: true,
    description: "Potato 1kg",
    isFavourite: false,
    title: "Potato 1kg",
    productCategory: "Vegetables",
    newPrice: 80,
    oldPrice: 100,
    discount: 20,
    outOfStock: false,
    isFast: false,
    itemCategory: "vegetables",
    itemRating: 3.8
  },
  {
    _id: uuid(),
    imgUrl: product28,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Cauliflower 500-600g",
    productCategory: "Vegetables",
    newPrice: 50,
    oldPrice: 80,
    discount: 30,
    outOfStock: false,
    isFast: true,
    itemCategory: "vegetables",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl: product29,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Green Chilies",
    productCategory: "Vegetables",
    newPrice: 30,
    oldPrice: 60,
    discount: 50,
    outOfStock: false,
    isFast: false,
    itemCategory: "vegetables",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl: product30,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Cabbage",
    productCategory: "Vegetables",
    newPrice: 80,
    oldPrice: 160,
    discount: 50,
    outOfStock: false,
    isFast: true,
    itemCategory: "vegetables",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl: product31,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Lady's Finger",
    productCategory: "Vegetables",
    newPrice: 80,
    oldPrice: 160,
    discount: 50,
    outOfStock: false,
    isFast: false,
    itemCategory: "vegetables",
    itemRating: 4.8
  },
  {
    _id: uuid(),
    imgUrl: product32,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Ginger Fresh",
    productCategory: "Vegetables",
    newPrice: 100,
    oldPrice: 180,
    discount: 60,
    outOfStock: true,
    isFast: false,
    itemCategory: "vegetables",
    itemRating: 4.8
  },

  {
    _id: uuid(),
    imgUrl: product33,
    isTrending: false,
    description: "live Collection",
    isFavourite: false,
    title: "Capsicum Green",
    productCategory: "Vegetables",
    newPrice: 100,
    oldPrice: 180,
    discount: 60,
    outOfStock: true,
    isFast: false,
    itemCategory: "vegetables",
    itemRating: 4.8
  }
  
  
  
];
