import { v4 as uuid } from "uuid";

export const products = [
  {
    id: uuid(),
    imgUrl: "https://therightfit.netlify.app/assets/shoes.jpg",
    isTrending: false,
    description: "Mens Feather WeightWhite Orange Sneakers",
    isFavourite: false,
    title: "Nike",
    productCategory: "Men Sneakers",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 67,
    outOfStock: false,
    isFast: true,
    itemCategory: "Ghee",
    itemRating: 4.8
  },
  {
    id: uuid(),
    imgUrl:
      "https://rukminim2.flixcart.com/image/332/398/kthjy4w0/shoe/h/h/x/5-gug87-adidas-cblack-clelil-ftwwht-original-imag6tgyzy3tjf5v.jpeg?q=50",
    isTrending: true,
    isFavourite: false,
    title: "Adidas",
    productCategory: "Women Shoes",
    description: "Womens Feather WeightWhite Orange Sneakers",
    newPrice: 750,
    oldPrice: 1499,
    discount: 75,
    outOfStock: true,
    isFast: true,
    itemCategory: "Honey",
    itemRating: 3.9
  },
  {
    id: uuid(),
    imgUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nikko_black_sandal.jpg/800px-Nikko_black_sandal.jpg",
    isTrending: false,
    isFavourite: false,
    description: "Mens Feather WeightWhite Orange Sneakers",
    title: "Bata",
    productCategory: "Boys Sandals",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 46,
    outOfStock: false,
    isFast: false,
    itemCategory: "oils",
    itemRating: 2.9
  },
  {
    id: uuid(),
    imgUrl: "https://therightfit.netlify.app/assets/shoes.jpg",
    isTrending: true,
    isFavourite: false,
    description: "Mens Feather WeightWhite Orange Sneakers",
    title: "Sparx",
    productCategory: "Girls Shoes - Premium",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 33,
    outOfStock: false,
    isFast: false,
    itemCategory: "Butter",
    itemRating: 1.1
  },
  {
    id: uuid(),
    imgUrl: "https://therightfit.netlify.app/assets/shoes.jpg",
    isTrending: false,
    isFavourite: false,
    description: "Mens Feather Weight White Orange Sneakers",
    title: "Nike",
    productCategory: "Girls Shoes - Premium",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 21,
    outOfStock: false,
    isFast: true,
    itemCategory: "Butter",
    itemRating: 1.8
  },
  {
    id: uuid(),
    imgUrl:
      "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw72da6744/images/a_08/A01735C_A_08X1.jpg?sw=406",
    isTrending: true,
    isFavourite: false,
    title: "All Star",
    productCategory: "Boys Converse",
    description: "Mens Feather WeightWhite Orange Sneakers",
    newPrice: 1750,
    oldPrice: 2499,
    discount: 27,
    outOfStock: true,
    isFast: true,
    itemCategory: "oils",
    itemRating: 2.5
  },
  {
    id: uuid(),
    imgUrl:
      "https://cdn.lifestyleasia.com/wp-content/uploads/2019/08/20153351/6e03e37670a9089e01e24eeddc9eee8b.jpeg",
    isTrending: false,
    isFavourite: false,
    title: "Addidas Collection",
    productCategory: "Addidas Vintage for Men",
    newPrice: 3750,
    description: "Mens Feather WeightWhite Orange Sneakers",
    oldPrice: 4499,
    discount: 90,
    outOfStock: false,
    isFast: false,
    itemCategory: "Ghee",
    itemRating: 3.6
  },
  {
    id: uuid(),
    imgUrl: "https://therightfit.netlify.app/assets/shoes.jpg",
    isTrending: false,
    isFavourite: false,
    title: "Nike",
    productCategory: "Girls Running Shoes",
    description: "Mens Feather WeightWhite Orange Sneakers",
    newPrice: 2750,
    oldPrice: 3499,
    discount: 44,
    outOfStock: true,
    isFast: true,
    itemCategory: "Butter",
    itemRating: 4.2
  },
  {
    id: uuid(),
    imgUrl: "https://therightfit.netlify.app/assets/shoes.jpg",
    isTrending: true,
    isFavourite: false,
    title: "Puma",
    productCategory: "Women Running Shoes",
    description: "Mens Feather WeightWhite Orange Sneakers",
    newPrice: 3750,
    oldPrice: 4499,
    discount: 39,
    outOfStock: false,
    isFast: true,
    itemCategory: "Honey",
    itemRating: 4.5
  },
];
